<a href="https://colab.research.google.com/github/angel870326/XLNet_Text_Classification/blob/main/brand/brand_final_result.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> 2022.06.12 Ssu-Yun Wang<br/>
[Github @angel870326](https://github.com/angel870326)

# **品牌最終結果**

### Contents:

*   更新原有品牌清單更名者
*   品牌統一清單
*   XLNet
*   BERT 0.85以上
*   Web Craw New Brand
*   品牌更新答案清單
*   沒有找到的新品牌以 XLNet 預測結果替代
*   輸出最終結果
*   合併至原測試資料集

In [1]:
import numpy as np
import pandas as pd
from collections import Counter
import re

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## **更新原有品牌清單更名者**

In [3]:
def new_brand_name(df, col_name):
  df[col_name] = df[col_name].replace(['tide','naturalsbywatsons','more','家福carrefour','大拇指fp','luna'],['汰漬tide','屈臣氏watsons','多喝水','家樂福','大潤發','佳麗寶kanebo'])

## **品牌統一清單**

In [4]:
brand_list = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/品牌/品牌清單/brand_dict_final.csv')
brand_list.columns = ['id', 'original', 'organized']
brand_list

        id           original         organized
0        0             21Plus            21plus
1        1               21世紀            21plus
2        2     一家人 OUR FAMILY      一家人ourfamily
3        3                一家人      一家人ourfamily
4        4                 九陽         九陽joyoung
...    ...                ...               ...
1157  1157                 元氣                vv
1158  1158  Yvonne Collection  yvonnecollection
1159  1159  yvonne collection  yvonnecollection
1160  1160                 Za                za
1161  1161                 ZA                za

[1162 rows x 3 columns]

In [5]:
original_brand = brand_list["original"].to_numpy()
organized_brand = brand_list["organized"].to_numpy()
original_brand

array(['21Plus', '21世紀', '一家人 OUR FAMILY', ..., 'yvonne collection', 'Za',
       'ZA'], dtype=object)

In [6]:
def update_brand_list(df, col_name):
  df[col_name] = df[col_name].replace(original_brand, organized_brand)

## **XLNet**


---

In [7]:
brand_xlnet = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/output/final/xlnet_brand_single_predict_bcel.csv')
new_brand_name(brand_xlnet, 'brand_predict')
update_brand_list(brand_xlnet, 'brand_predict')
brand_xlnet

          id                                  name  max_prob   brand_predict
0          0             heme喜蜜輕透柔光粉底液spf5030ml2入組   0.99521          喜蜜heme
1          1                   肌研卵肌溫和去角質化粧水170ml2入   0.97716       日本樂敦rohto
2          2                            cm康媚絲洗髮精強化   0.07440  MAYBELLINE 媚比琳
3          3                           br超柔潤保濕面膜5片   0.97705  Barrier Repair
4          4  即期品買1送1dejavu睫采分明立體睫毛膏黑色31g效期2022630   0.08635          dejavu
...      ...                                   ...       ...             ...
97154  97154                  石澤研究所毛穴撫子角質對策泡洗顏100g   0.06031            齒磨撫子
97155  97155                         金牌台灣啤酒330ml6入   0.99694            台灣啤酒
97156  97156                               日清中杯麵醬油   0.98917              日清
97157  97157                           杜蕾斯活力裝衛生套個盒   0.00614            大衛杜夫
97158  97158                 小米11litene5g手機8g256g網   0.89139        小米xiaomi

[97159 rows x 4 columns]

## **BERT 0.85以上**

---
by [Meng-Chieh, Liu](https://github.com/MengChiehLiu)

In [8]:
brand_result = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/孟頡/test_data_0.85.csv')
brand_result.columns = ['id', 'name', 'brand']
new_brand_name(brand_result, 'brand')
update_brand_list(brand_result, 'brand')
brand_result

          id                                  name           brand
0          0             heme喜蜜輕透柔光粉底液spf5030ml2入組          喜蜜heme
1          1                   肌研卵肌溫和去角質化粧水170ml2入       日本樂敦rohto
2          2                            cm康媚絲洗髮精強化  MAYBELLINE 媚比琳
3          3                           br超柔潤保濕面膜5片  Barrier Repair
4          4  即期品買1送1dejavu睫采分明立體睫毛膏黑色31g效期2022630          dejavu
...      ...                                   ...             ...
97154  97154                  石澤研究所毛穴撫子角質對策泡洗顏100g            毛穴撫子
97155  97155                         金牌台灣啤酒330ml6入            台灣啤酒
97156  97156                               日清中杯麵醬油              日清
97157  97157                           杜蕾斯活力裝衛生套個盒           Other
97158  97158                 小米11litene5g手機8g256g網        小米xiaomi

[97159 rows x 3 columns]

## **Web Craw New Brand**


---
by [Meng-Chieh, Liu](https://github.com/MengChiehLiu)

In [9]:
webcraw = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/孟頡/new_brands_v3.csv')
webcraw.columns = ['id', 'name', 'new_brand']
new_brand_name(webcraw, 'new_brand')
update_brand_list(webcraw, 'new_brand')
webcraw

,id,name,new_brand
0,12,0772163285一度贊剝皮辣椒雞肉麵,維力
1,15,歐規床包專區床包長度200cm60支精梳棉無印良品ikea尺寸多款可選100精梳棉台灣製造,棉床本舖
2,23,snapware康寧密扣全新升級圓形寶寶用玻璃保鮮盒150ml3入裝,CorelleBrands 康寧餐具
3,25,fbo維e舒緩面膜4,Neogence 霓淨思
4,29,狗狗這樣吃不生病良心獸醫教你46道超簡單的手作健康狗料理從營養補充調理體質到對症食療一本搞定,蘋果屋
...,...,...,...
10992,97135,yadah綠茶純淨潔膚卸妝膏100ml卸妝兼去角質回購率超高韓國卸妝膏溫和不緊繃短效特賣,yadah
10993,97138,毛寶制臭極淨pm25洗衣精補充包2000gx3入,毛寶
10994,97142,ysl極效活萃夜光仙人掌超級精華30ml,YSL
10995,97151,旺旺生活八犬8dogs原町燒肉原町台灣天然手作寵物零食狗零食台灣本產手工肉片狗狗肉條肉絲,8DOG'S 八犬
10996,97157,杜蕾斯活力裝衛生套個盒,Durex 杜蕾斯

In [10]:
for i in webcraw.index:
  brand_result.loc[brand_result['id'] == webcraw.loc[i,'id'], 'brand'] = webcraw.loc[i,'new_brand']
brand_result

          id                                  name           brand
0          0             heme喜蜜輕透柔光粉底液spf5030ml2入組          喜蜜heme
1          1                   肌研卵肌溫和去角質化粧水170ml2入       日本樂敦rohto
2          2                            cm康媚絲洗髮精強化  MAYBELLINE 媚比琳
3          3                           br超柔潤保濕面膜5片  Barrier Repair
4          4  即期品買1送1dejavu睫采分明立體睫毛膏黑色31g效期2022630          dejavu
...      ...                                   ...             ...
97154  97154                  石澤研究所毛穴撫子角質對策泡洗顏100g            毛穴撫子
97155  97155                         金牌台灣啤酒330ml6入            台灣啤酒
97156  97156                               日清中杯麵醬油              日清
97157  97157                           杜蕾斯活力裝衛生套個盒       Durex 杜蕾斯
97158  97158                 小米11litene5g手機8g256g網        小米xiaomi

[97159 rows x 3 columns]

## **品牌更新答案清單**


---
人工核對 BERT 0.85 以上預測錯誤<br/>
XLNet 0.5 以上預測正確者

In [11]:
modify_list = pd.read_excel("/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/比較與統整/品牌/brand_modify_list.xlsx")
modify_list = modify_list.astype({"id": int})
new_brand_name(modify_list, 'brand')
update_brand_list(modify_list, 'brand')
modify_list

,id,name,brand
0,21,日本pg2021新版bold3d洗衣球補充包超值三入組138顆189顆桂花清香牡丹花香日本必...,寶僑ariel
1,240,c023500015超完美持久柔霧粉底液15n,迪奧dior
2,1272,asus華碩vivowatchsp智慧手錶hca05即時血氧偵測可指尖量測,華碩 ASUS
3,1357,187彩妝刷,M.A.C
4,1382,12粉持久持妝粉底,Estée Lauder 雅詩蘭黛
...,...,...,...
392,95739,日本skater012歲透明款兒童卡通牙刷角落生物迪士尼軟毛牙刷三入組多款任選,SKATER
393,95798,ecadidas慢跑鞋,愛迪達adidas
394,95816,免運莫比mobby挑嘴成貓饕客配方15kg3kg75kg莫比貓挑嘴貓貓飼料xinwei,莫比 Mobby
395,96081,11065327257743philips43pfh5714液晶電視296485,飛利浦philips
396,96193,sukin經典基礎保濕乳液125ml,sukin

In [12]:
for i in modify_list.index:
  brand_result.loc[brand_result['id'] == modify_list.loc[i,'id'], 'brand'] = modify_list.loc[i,'brand']
brand_result

          id                                  name           brand
0          0             heme喜蜜輕透柔光粉底液spf5030ml2入組          喜蜜heme
1          1                   肌研卵肌溫和去角質化粧水170ml2入       日本樂敦rohto
2          2                            cm康媚絲洗髮精強化  MAYBELLINE 媚比琳
3          3                           br超柔潤保濕面膜5片  Barrier Repair
4          4  即期品買1送1dejavu睫采分明立體睫毛膏黑色31g效期2022630          dejavu
...      ...                                   ...             ...
97154  97154                  石澤研究所毛穴撫子角質對策泡洗顏100g            毛穴撫子
97155  97155                         金牌台灣啤酒330ml6入            台灣啤酒
97156  97156                               日清中杯麵醬油              日清
97157  97157                           杜蕾斯活力裝衛生套個盒       Durex 杜蕾斯
97158  97158                 小米11litene5g手機8g256g網        小米xiaomi

[97159 rows x 3 columns]

## **沒有找到的新品牌以 XLNet 預測結果替代**


---

In [13]:
zero_filter = brand_result["brand"].isin(["0","Other","other"])
zero = brand_result.loc[zero_filter,:]
zero

          id                                           name brand
318      318               新春特惠法式舒肥嫩雞胸肉買12送12共24包再送12包綜合蔬菜網     0
360      360          nickshop50顆洗衣膠球2入組共100顆去汙去除異味柔順衣物遇水速溶     0
510      510                                        雞尾酒葡萄沙瓦     0
635      635    台灣新格sgcb八段式水槍花灑水槍低壓水軟水園藝用水槍汽車美容洗車水管水槍可調節式水槍     0
665      665                                狗共饗食堂純手作100g雞肉條     0
...      ...                                            ...   ...
95650  95650    暢銷排行no1紅包888現折限時43折加碼送康寧餐盤啟動四重代謝力孅益薑黃100粒4瓶     0
96124  96124                                       檀島凍檸茶雞尾酒     0
96634  96634  超商取貨最多3瓶takeappeal香飾質感香氛柔軟精1000ml衣物高濃縮防靜電安全成分     0
96774  96774                 盒損良品8入組極淨適茶樹精油柔嫩護手霜清新綠茶35mlx8支     0
97017  97017      代收代付佐登妮絲光感保濕cc霜spf30亮膚色自然色30g效期202317一隻阿圓     0

[289 rows x 3 columns]

In [14]:
for i in zero.index:
  brand_result.loc[i, 'brand'] = brand_xlnet.loc[i,'brand_predict']
brand_result

          id                                  name           brand
0          0             heme喜蜜輕透柔光粉底液spf5030ml2入組          喜蜜heme
1          1                   肌研卵肌溫和去角質化粧水170ml2入       日本樂敦rohto
2          2                            cm康媚絲洗髮精強化  MAYBELLINE 媚比琳
3          3                           br超柔潤保濕面膜5片  Barrier Repair
4          4  即期品買1送1dejavu睫采分明立體睫毛膏黑色31g效期2022630          dejavu
...      ...                                   ...             ...
97154  97154                  石澤研究所毛穴撫子角質對策泡洗顏100g            毛穴撫子
97155  97155                         金牌台灣啤酒330ml6入            台灣啤酒
97156  97156                               日清中杯麵醬油              日清
97157  97157                           杜蕾斯活力裝衛生套個盒       Durex 杜蕾斯
97158  97158                 小米11litene5g手機8g256g網        小米xiaomi

[97159 rows x 3 columns]

## **輸出最終結果**



---

In [15]:
brand_result.to_csv("/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/最終結果/brand_result.csv")

In [16]:
brand_count = Counter(brand_result['brand'].values)
brand_count_df = pd.DataFrame(list(brand_count.items()), columns=['Brand', 'Count'])
brand_count_df

               Brand  Count
0             喜蜜heme    215
1          日本樂敦rohto    297
2     MAYBELLINE 媚比琳    574
3     Barrier Repair      4
4             dejavu     59
...              ...    ...
5251            okja      1
5252         CALIMBA      1
5253          PAMABE      1
5254           yadah      1
5255      Cosplus 光妍      1

[5256 rows x 2 columns]

## **合併至原測試資料集**


---

In [17]:
test = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/資料檔/原始資料/brand_test(question).csv')
test

,name,occurred_at,iv_price,brand,units,unit_price,total_price,channel
0,【heme 喜蜜】輕透柔光粉底液 SPF50+ ★★★ - 30ml(2入組),2022-02-03,2558,NaN,1.0,470.0,470.0,bceb22fe7ebb8d831758f603636b37ec
1,【肌研】卵肌溫和去角質化粧水170ml 2入,2022-02-05,860,NaN,1.0,430.0,430.0,bceb22fe7ebb8d831758f603636b37ec
2,"C.M康媚絲洗髮精,強化",2022-02-07,2280,NaN,1.0,369.0,369.0,8c75bf3b3f5083dccb46024354c128f5
3,BR超柔潤保濕面膜 5片,2022-02-02,516,NaN,1.0,199.0,99.0,2c2cc93adb503077c729a911c56c33b9
4,(即期品)(買1送1)dejavu 睫采分明立體睫毛膏_黑色3.1g(效期2022/6/30),2022-02-09,272,NaN,1.0,272.0,272.0,e8f071c97ddf0483d2e3fd7832a5313f
...,...,...,...,...,...,...,...,...
97154,石澤研究所毛穴撫子角質對策泡洗顏100g,2022-02-11,839,NaN,1.0,420.0,420.0,5b2c23969eb3b259b19fbfd81a8bcb4e
97155,金牌台灣啤酒330ml6入,2022-02-02,380,NaN,2.0,159.0,318.0,5b619d1dffc5d5305becf5c35a137534
97156,日清 中杯麵 醬油,2022-02-02,995,NaN,1.0,79.0,79.0,0bd95d8c19291c34027875117122a610
97157,杜蕾斯活力裝衛生套３個／盒,2022-02-02,278,NaN,1.0,110.0,110.0,792da55115fd6b0b543e549b20e5b957
97158,小米 11 Lite NE 5G手機 (8G/256G)-網,2022-02-01,9480,NaN,1.0,9480.0,9480.0,6a4c96566ada92771d6a377de7ad38b3

In [18]:
test['brand'] = brand_result['brand']
test

,name,occurred_at,iv_price,brand,units,unit_price,total_price,channel
0,【heme 喜蜜】輕透柔光粉底液 SPF50+ ★★★ - 30ml(2入組),2022-02-03,2558,喜蜜heme,1.0,470.0,470.0,bceb22fe7ebb8d831758f603636b37ec
1,【肌研】卵肌溫和去角質化粧水170ml 2入,2022-02-05,860,日本樂敦rohto,1.0,430.0,430.0,bceb22fe7ebb8d831758f603636b37ec
2,"C.M康媚絲洗髮精,強化",2022-02-07,2280,MAYBELLINE 媚比琳,1.0,369.0,369.0,8c75bf3b3f5083dccb46024354c128f5
3,BR超柔潤保濕面膜 5片,2022-02-02,516,Barrier Repair,1.0,199.0,99.0,2c2cc93adb503077c729a911c56c33b9
4,(即期品)(買1送1)dejavu 睫采分明立體睫毛膏_黑色3.1g(效期2022/6/30),2022-02-09,272,dejavu,1.0,272.0,272.0,e8f071c97ddf0483d2e3fd7832a5313f
...,...,...,...,...,...,...,...,...
97154,石澤研究所毛穴撫子角質對策泡洗顏100g,2022-02-11,839,毛穴撫子,1.0,420.0,420.0,5b2c23969eb3b259b19fbfd81a8bcb4e
97155,金牌台灣啤酒330ml6入,2022-02-02,380,台灣啤酒,2.0,159.0,318.0,5b619d1dffc5d5305becf5c35a137534
97156,日清 中杯麵 醬油,2022-02-02,995,日清,1.0,79.0,79.0,0bd95d8c19291c34027875117122a610
97157,杜蕾斯活力裝衛生套３個／盒,2022-02-02,278,Durex 杜蕾斯,1.0,110.0,110.0,792da55115fd6b0b543e549b20e5b957
97158,小米 11 Lite NE 5G手機 (8G/256G)-網,2022-02-01,9480,小米xiaomi,1.0,9480.0,9480.0,6a4c96566ada92771d6a377de7ad38b3

In [19]:
test.to_csv("/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/最終結果/brand_test(question).csv")