<a href="https://colab.research.google.com/github/angel870326/XLNet_Text_Classification/blob/main/product/oversampling_product.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> 2022.06.07 Ssu-Yun Wang<br/>
[Github @angel870326](https://github.com/angel870326)

# **品類過採樣（Oversampling for Product）**

### **Contents:**

*   清理後的資料
*   區分出大於30筆&小於30筆的資料
*   **小於30筆者過採樣(oversampling)至100筆***
*   合併

In [ ]:
import numpy as np
import pandas as pd
from collections import Counter
import re

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## **清理後的資料**

In [ ]:
# Cleaned dataset
product_train_or = pd.read_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/資料集/category_clean1.csv')
product_train_or

       Unnamed: 0                     name product
0               0         r視舒坦單支裝人工淚液點眼液 入    人工淚液
1               1                   優麗舒點眼液    人工淚液
2               2                r視舒坦單支裝人工    人工淚液
3               3                rohto乾眼淚液    人工淚液
4               4             r參天柔潤人工淚液點眼液    人工淚液
...           ...                      ...     ...
91848       92301      mdmmd微醺心機漸層腮紅玫瑰瑪格麗特      腮紅
91849       92302          mdmmd微醺心機漸層腮紅橙酒      腮紅
91850       92303     倫敦芮魅 叛逆玩色腮紅盤005 微醺酒紅      腮紅
91851       92304     palladio柔光幻彩貝殼腮紅微醺蜜桃      腮紅
91852       92305  韓國 eglips粉嫩微醺美肌花瓣腮紅6色可選      腮紅

[91853 rows x 3 columns]

In [ ]:
# product counter
product_train_or['counter'] = product_train_or.groupby('product')['product'].transform('count')
product_train_or

       Unnamed: 0                     name product  counter
0               0         r視舒坦單支裝人工淚液點眼液 入    人工淚液      114
1               1                   優麗舒點眼液    人工淚液      114
2               2                r視舒坦單支裝人工    人工淚液      114
3               3                rohto乾眼淚液    人工淚液      114
4               4             r參天柔潤人工淚液點眼液    人工淚液      114
...           ...                      ...     ...      ...
91848       92301      mdmmd微醺心機漸層腮紅玫瑰瑪格麗特      腮紅      368
91849       92302          mdmmd微醺心機漸層腮紅橙酒      腮紅      368
91850       92303     倫敦芮魅 叛逆玩色腮紅盤005 微醺酒紅      腮紅      368
91851       92304     palladio柔光幻彩貝殼腮紅微醺蜜桃      腮紅      368
91852       92305  韓國 eglips粉嫩微醺美肌花瓣腮紅6色可選      腮紅      368

[91853 rows x 4 columns]

## **區分出大於30筆&小於30筆的資料**

In [ ]:
# 大於30筆
product_train_large = product_train_or[product_train_or.counter > 30]
product_train_large

       Unnamed: 0                     name product  counter
0               0         r視舒坦單支裝人工淚液點眼液 入    人工淚液      114
1               1                   優麗舒點眼液    人工淚液      114
2               2                r視舒坦單支裝人工    人工淚液      114
3               3                rohto乾眼淚液    人工淚液      114
4               4             r參天柔潤人工淚液點眼液    人工淚液      114
...           ...                      ...     ...      ...
91848       92301      mdmmd微醺心機漸層腮紅玫瑰瑪格麗特      腮紅      368
91849       92302          mdmmd微醺心機漸層腮紅橙酒      腮紅      368
91850       92303     倫敦芮魅 叛逆玩色腮紅盤005 微醺酒紅      腮紅      368
91851       92304     palladio柔光幻彩貝殼腮紅微醺蜜桃      腮紅      368
91852       92305  韓國 eglips粉嫩微醺美肌花瓣腮紅6色可選      腮紅      368

[91442 rows x 4 columns]

In [ ]:
# 小於30筆
product_train_small = product_train_or[product_train_or.counter <= 30]
product_train_small

       Unnamed: 0                                   name product  counter
1284         1291                      all clean 兒童伯肯鞋軍綠  水路/健行鞋        4
1285         1292    salomon 法國女 xa pro 3d v8 gtx健野鞋黑黑幻灰  水路/健行鞋        4
1286         1293          moonstar 月星戶外多功能系列防水抗菌戶外悠閒鞋卡其  水路/健行鞋        4
1287         1294                      all clean 兒童伯肯鞋軍綠  水路/健行鞋        4
1814         1821                               新彩虹巧拼墊60    巧拼地墊       19
...           ...                                    ...     ...      ...
91338       91755                userism物理柔霧防曬dd霜spf50瓶組     DD霜       13
91339       91756  userism 靓肌靓 物理柔霧防曬dd霜  dd霜 spf50  迷你瓶     DD霜       13
91340       91757                           drwu超保濕水感dd霜     DD霜       13
91341       91758                          物理性防曬 dd霜 亮膚色     DD霜       13
91342       91759              userism 靓肌靚物理柔霧防曬dd霜spf50     DD霜       13

[411 rows x 4 columns]

In [ ]:
# 小於30筆的品類
product_count = Counter(product_train_small['product'].values)
product_count_df = pd.DataFrame(list(product_count.items()), columns=['Product', 'Count']).sort_values(by=['Count'])
product_count_df

     Product  Count
23        槓片      3
5        卸甲液      3
8        保溫杯      3
0     水路/健行鞋      4
25      嬰幼乳液      4
24     嬰幼手推車      6
20  媽媽茶(哺乳茶)      9
7        卸妝露     10
13       唇彩盤     13
26       DD霜     13
12      原味牛乳     14
16       健腹器     15
19       眼影霜     16
9       前導精華     16
15       烤肉架     17
6       卸妝濕巾     17
22       溫奶器     17
1       巧拼地墊     19
2        甲油膠     20
4         羊乳     21
10       按摩椅     22
14       唇線筆     23
11       洗碗機     23
17      眼影打底     23
18       眼影蜜     25
3       媽媽奶粉     25
21        椰奶     30

## **小於30筆者過採樣(oversampling)至100筆**

In [ ]:
from sklearn.utils import resample
filter_1 = product_train_small["product"].isin([product_count_df.iloc[0,0]])
product_1 = product_train_small.loc[filter_1,:]
oversample = resample(product_1,
           replace = True,
           n_samples = 100,
           random_state = 42)

for i in range(1, product_count_df.shape[0]):
  filter_i = product_train_small["product"].isin([product_count_df.iloc[i,0]])
  product_i = product_train_small.loc[filter_i,:]
  oversample_i = resample(product_i,
             replace = True,
             n_samples = 100,
             random_state = 42)
  oversample = pd.concat([oversample, oversample_i])

oversample

       Unnamed: 0                              name product  counter
68931       69269                            槓片短槓心a      槓片        3
68929       69267  體育刻tuk奧林匹克槓片 – 125  25  5 kg tuk      槓片        3
68931       69269                            槓片短槓心a      槓片        3
68931       69269                            槓片短槓心a      槓片        3
68929       69267  體育刻tuk奧林匹克槓片 – 125  25  5 kg tuk      槓片        3
...           ...                               ...     ...      ...
59348       59683                            koh 椰奶      椰奶       30
59337       59672                        泰國teptip椰奶      椰奶       30
59345       59680                         koh酷椰嶼椰奶       椰奶       30
59331       59666                           vico 椰奶      椰奶       30
59321       59656                        愛之味莎莎亞椰奶組組      椰奶       30

[2700 rows x 4 columns]

## **合併**

In [ ]:
product_train = pd.concat([oversample, product_train_large])
product_train

       Unnamed: 0                              name product  counter
68931       69269                            槓片短槓心a      槓片        3
68929       69267  體育刻tuk奧林匹克槓片 – 125  25  5 kg tuk      槓片        3
68931       69269                            槓片短槓心a      槓片        3
68931       69269                            槓片短槓心a      槓片        3
68929       69267  體育刻tuk奧林匹克槓片 – 125  25  5 kg tuk      槓片        3
...           ...                               ...     ...      ...
91848       92301               mdmmd微醺心機漸層腮紅玫瑰瑪格麗特      腮紅      368
91849       92302                   mdmmd微醺心機漸層腮紅橙酒      腮紅      368
91850       92303              倫敦芮魅 叛逆玩色腮紅盤005 微醺酒紅      腮紅      368
91851       92304              palladio柔光幻彩貝殼腮紅微醺蜜桃      腮紅      368
91852       92305           韓國 eglips粉嫩微醺美肌花瓣腮紅6色可選      腮紅      368

[94142 rows x 4 columns]

In [ ]:
product_train.to_csv('/content/drive/MyDrive/碩一下/金融科技/麻布數據/第四組/資料集/category_clean1_oversample.csv', index = False)